### PR TITLE
surface custom tracking attribute

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by adgad** [comment]
What's the use case?

**Comment by wheresrhys** [comment]
different teasers in recommendations will be there for different reasons

**Comment by adgad** [comment]
I wonder if it's better to add as a context attribute. (just because it might make it harder to query across teasers by changing the name)
something like `data-trackable-context-reason="blah"`

**Comment by wheresrhys** [comment]
yep good point. Not sure how that works in o-tracking, but will investigate

**Comment by wheresrhys** [comment]
I've gone with calling the property 'originator'

**Pull request merged**
