### PR TITLE
add flag to denote potential syndication

### PR DESCRIPTION
**Pull request by aintgoin2goa**
@keirog @andygnewman

### CODE REVIEW

**Comment by andygnewman** [comment]
Does this appear to all users?

**Comment by aintgoin2goa** [comment]
The class appears, but not anything else.  In order to download an article it needs to be permitted for syndication AND the user needs to be a syndication customer.

This modifier will be picked up by some js in n-ui which will show a little green tick next to the title

**Comment by andygnewman** [comment]
Will the little green tick be visible to all or does the JS in n-ui only show it if the user is a syndication customer?

**Comment by aintgoin2goa** [comment]
Only for syndication customers

**Comment by andygnewman** [comment]
👍

**Pull request merged**
