### PR TITLE
Fix bug assuming a package has a design property

### PR DESCRIPTION
**Pull request by i-like-robots**
It broked my streams build https://circleci.com/gh/Financial-Times/next-stream-page/6251

### CODE REVIEW

**Comment by adgad** [comment]
👍  your one looks nicer

**Comment by i-like-robots** [comment]
Why thank you, I thought yours was equally dashing

**Comment by i-like-robots** [comment]
Bugger.

**Comment by i-like-robots** [comment]
Nevermind

**Comment by i-like-robots** [comment]
You have to comment to reopen 😆

**Pull request merged**
